### ISSUE TITLE
Microanut-Ktor blocks within the start function 

### ISSUE THREAD

**Issue by aditya7k** [micronaut-projects/micronaut-kotlin#364] opened 2022-02-23 13:56 UTC
### Expected Behavior

The Micronaut start function should return the ApplicationContext.

### Actual Behaviour

 The start function does not return because isKeepAlive() in AbstractKtorEmbeddedServer is not overriden to return false.

Overriding isKeepAlive() in AbstractKtorEmbeddedServer fixes the problem.

This is in micronaut-ktor version 3.2.0.

### Version

3.3.3

**Comment by timyates** [comment] 2023-05-03 11:00
Unfortunately, the fix stopped standalone Ktor apps from running (well, it made them stop straight away)

Do you have a reproducer showing the issue which we can roll up into a test to make sure we support both things?

**Comment by sdelamo** [comment] 2023-08-30 15:03
Closing this issue, please @aditya7k reopen if the issue is still present.

**Closed by sdelamo** 2023-08-30 15:03 UTC
Labels: info: good first issue, status: awaiting feedback
